name: tony-debug

on:
  pull_request:
    branches: ["dev"]
    types: [labeled, synchronize, opened, reopened]
  workflow_dispatch:
jobs:
  stagefcm_noram:
    name: Run E2E STAGEFCM_NORAM
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'STAGEFCM_NORAM')
    runs-on: self-hosted
  stage_noram:
    name: Run E2E STAGE_NORAM
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'STAGE_NORAM')
    runs-on: self-hosted
